[Running] Function getUserDetailsByIdTryCatch
===== Input set number 0 =====
Function inputs:
userId:  -1
Function output:
Function throws an exception:
Class: Error
Message: Given user ID is invalid. Got: -1, expected value >=0

===== Input set number 1 =====
Function inputs:
userId:  0
Function output:
Function throws an exception:
Class: Error
Message: Error fetching data from API

===== Input set number 2 =====
Function inputs:
userId:  1
Function output:
{ username: 'Bret', name: 'Leanne Graham', email: 'Sincere@april.biz' }


[Done] exited with code=0